=== pontused/stuff-1-2016/hw1/out/production/hw1/xml/schemas/personemployments.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.personemployments.com"
           xmlns="http://www.personemployments.com"
           elementFormDefault="qualified">


    <xsd:element name="personemployments" type="person"/>

    <xsd:complexType name="person">
        <xsd:sequence>
            <xsd:element name="person" type="personObject" minOccurs="0" maxOccurs="unbounded" />

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="personObject">
        <xsd:sequence>
            <xsd:element name="firstname" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-öA-Ö]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="lastname" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-öA-Ö]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="ssn" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]{10}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="workhistory" type="employment" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="employment">
        <xsd:sequence>
            <xsd:element name="companyName" type="xsd:string"/>
            <xsd:element name="orgNumber" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]{6}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="employmentRole" type="xsd:string"/>
            <xsd:element name="startDate" type="xsd:date"/>
            <xsd:element name="endDate" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== pontused/stuff-1-2016/hw1/src/xml/employment.xml
<person:personemployments
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns:person ='http://www.personemployments.com'
        xmlns:emp = 'http://www.employment.com'
        xsi:schemaLocation='http://www.personemployments.com schemas/personemployments.xsd'>

    <person:person>
        <person:firstname>Peter</person:firstname>
        <person:lastname>Ledberg</person:lastname>
        <person:ssn>8003456378</person:ssn>
        <person:workhistory>
            <person:companyName>IBM</person:companyName>
            <person:orgNumber>123456</person:orgNumber>
            <person:employmentRole>Support</person:employmentRole>
            <person:startDate>2012-02-13</person:startDate>
            <person:endDate>2012-02-13</person:endDate>
        </person:workhistory>
        <person:workhistory>
            <person:companyName>KTH</person:companyName>
            <person:orgNumber>094934</person:orgNumber>
            <person:employmentRole>Support</person:employmentRole>
            <person:startDate>2012-02-13</person:startDate>
            <person:endDate>2012-02-13</person:endDate>
        </person:workhistory>
    </person:person>



   <person:person>
       <person:firstname>Kristina</person:firstname>
       <person:lastname>Svensson</person:lastname>
       <person:ssn>7043423423</person:ssn>
       <person:workhistory>
           <person:companyName>KTH</person:companyName>
           <person:orgNumber>094934</person:orgNumber>
           <person:employmentRole>asd</person:employmentRole>
           <person:startDate>2012-02-13</person:startDate>
           <person:endDate>2012-02-13</person:endDate>
       </person:workhistory>
   </person:person>

</person:personemployments>
