=== pontused/stuff-1-2016/hw1/src/xml/schemas/persontranscript.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.persontranscript.com"
           xmlns="http://www.persontranscript.com"
            elementFormDefault="qualified">


    <xsd:element name="persontranscript" type="person"/>

    <xsd:complexType name="person">
        <xsd:sequence>
            <xsd:element name="person" type="personObject" minOccurs="0" maxOccurs="unbounded" />

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="personObject">
        <xsd:sequence>
            <xsd:element name="firstname" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-öA-Ö]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="lastname" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-öA-Ö]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="ssn" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]{10}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="program" type="schoolprogram" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="schoolprogram">
        <xsd:sequence>
            <xsd:element name="programName" type="xsd:string"/>
            <xsd:element name="universityName" type="xsd:string"/>
            <xsd:element name="course" type="courseTranscript" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="startDate" type="xsd:date"/>
            <xsd:element name="finishDate" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="courseTranscript">
        <xsd:sequence>
            <xsd:element name="courseName" type="xsd:string"/>
            <xsd:element name="courseNumber" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[A-Z]{2}[0-9]{4}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="degree" type="xsd:decimal">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:pattern value="[0-5]{1}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="startDate" type="xsd:date"/>
            <xsd:element name="finishedDate" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>


</xsd:schema>

=== pontused/stuff-1-2016/hw1/out/production/hw1/xml/transcript.xml
<transcript:persontranscript
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns:transcript ='http://www.persontranscript.com'
        xsi:schemaLocation='http://www.persontranscript.com schemas/persontranscript.xsd'>

    <transcript:person>
        <transcript:firstname>Peter</transcript:firstname>
        <transcript:lastname>Ledberg</transcript:lastname>
        <transcript:ssn>8003456378</transcript:ssn>
        <transcript:program>
            <transcript:programName>Distributed systems</transcript:programName>
            <transcript:universityName>KTH</transcript:universityName>
            <transcript:course>
                <transcript:courseName>Webservices</transcript:courseName>
                <transcript:courseNumber>ID2208</transcript:courseNumber>
                <transcript:degree>5</transcript:degree>
                <transcript:startDate>2016-01-18</transcript:startDate>
                <transcript:finishedDate>2016-03-15</transcript:finishedDate>
            </transcript:course>
            <transcript:course>
                <transcript:courseName>Distributed Systems, Advanced Course</transcript:courseName>
                <transcript:courseNumber>ID2203</transcript:courseNumber>
                <transcript:degree>4</transcript:degree>
                <transcript:startDate>2016-01-18</transcript:startDate>
                <transcript:finishedDate>2016-03-15</transcript:finishedDate>
            </transcript:course>
            <transcript:startDate>2015-08-30</transcript:startDate>
            <transcript:finishDate>2017-06-01</transcript:finishDate>
        </transcript:program>
    </transcript:person>


</transcript:persontranscript>
